Repository dnsimple/erldns, pull requests merged in 2024-10, with the labels that each got.

#160 Add a benchmarking guide
  BENCHMARKING.md
  README.md
Labels: task

#161 Update to OTP/27
  .github/workflows/ci.yml
  .tool-versions
Labels: enhancement

#134 erldns_udp_server: Fix flow control
  src/erldns_udp_server.erl
Labels: bug

#162 Check formatting in CI
  CONTRIBUTING.md
  Makefile
Labels: enhancement
